### ISSUE TITLE
Misuse of sync.WaitGroup

### ISSUE THREAD

**Issue by fjl** [Microsoft/go-winio#29]
With the test below, the following crash occurs instantly. The test is a bit
unwieldy, sorry about that. I am using Go 1.6 on Windows 10.
The documentation of package sync states that

>  If a WaitGroup is reused to wait for several independent sets of events, new Add calls must happen after all previous Wait calls have returned.

The runtime check for this invariant was added in Go 1.5.
I wonder why this issue hasn't come up yet.

``` text
=== RUN   TestCloseRace
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 369 [running]:
panic(0x572cc0, 0xc08209b460)
    C:/tools/go/src/runtime/panic.go:464 +0x3f4
sync.(*WaitGroup).Wait(0xc0820e3638)
    C:/tools/go/src/sync/waitgroup.go:129 +0x11b
github.com/microsoft/go-winio.(*win32File).closeHandle(0xc0820e3630)
    c:/Users/fjl/src/github.com/microsoft/go-winio/file.go:94 +0x62
github.com/microsoft/go-winio.(*win32File).Close(0xc0820e3630, 0x0, 0x0)
    c:/Users/fjl/src/github.com/microsoft/go-winio/file.go:103 +0x34
github.com/microsoft/go-winio.TestCloseRace.func1.1()
    c:/Users/fjl/src/github.com/microsoft/go-winio/pipe_test.go:293 +0x12d
created by time.goFunc
    C:/tools/go/src/time/sleep.go:129 +0x41
exit status 2
```

The test:

``` go
func TestCloseRace(t *testing.T) {
    l, err := ListenPipe(testPipeName, &PipeConfig{})
    if err != nil {
        t.Fatal(err)
    }

    var (
        maxCloseTimeout   = 100 * time.Millisecond
        numClients        = 10
        numConnsPerClient = 10
        writeDelay        = 30 * time.Millisecond
        writeData         = make([]byte, 100)
        wg                sync.WaitGroup
    )
    server := func() {
        defer wg.Done()
        defer l.Close()
        for {
            conn, err := l.Accept()
            if err != nil {
                t.Log("accept error:", err)
                return
            }
            // Kill the connection after a random delay.
            timeout := time.Duration(rand.Int63n(int64(maxCloseTimeout)))
            time.AfterFunc(timeout, func() {
                t.Logf("killing connection after %v", timeout)
                conn.Close()
            })
            go io.Copy(ioutil.Discard, conn)
        }
    }
    client := func() {
        defer wg.Done()
        for i := 0; i < numConnsPerClient; i++ {
            conn, err := DialPipe(testPipeName, nil)
            if err != nil {
                t.Log("dial error:", err)
                return
            }
            defer conn.Close()
            // Kill the connection after a random delay.
            timeout := time.Duration(rand.Int63n(int64(maxCloseTimeout)))
            time.AfterFunc(timeout, func() {
                t.Logf("killing client connection after %v", timeout)
                conn.Close()
            })
            // Write some data until the connection goes away.
            for {
                if _, err := conn.Write(writeData); err != nil {
                    t.Log("write error:", err)
                    break
                }
                time.Sleep(writeDelay)
            }
        }
    }

    wg.Add(1)
    go server()
    wg.Add(numClients)
    for i := 0; i < numClients; i++ {
        go client()
    }
    wg.Wait()
}
```

**Comment by dolmen** [comment]
I wonder why this issue hasn't been reviewed yet.

**Comment by darrenstahlmsft** [comment]
This is fixed now. Apologies for the (rather long) delay. We let this slip through the cracks, and will do a better effort to not let that happen again.

Thank you very much for the test @fjl, it was helpful in testing to confirm that the fix worked.
