### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by mappu** [Microsoft/go-winio#41]
Hi,

My go binary listens on a named pipe. All works fine normally, but I sometimes get this panic if the named pipe receives a connection:

```
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x40f115]

goroutine 18 [running]:
runtime.throw(0xa53f6f, 0x2a)
	C:/Go/src/runtime/panic.go:596 +0x9c fp=0xc042151e08 sp=0xc042151de8
runtime.sigpanic()
	C:/Go/src/runtime/signal_windows.go:155 +0x18b fp=0xc042151e38 sp=0xc042151e08
runtime.lock(0x5105fcc3b06b83db)
	C:/Go/src/runtime/lock_sema.go:43 +0x65 fp=0xc042151e70 sp=0xc042151e38
runtime.chansend(0x970300, 0x5105fcc3b06b8383, 0xc042151fb0, 0xc042151f01, 0x5d013a, 0xc042151f9c)
	C:/Go/src/runtime/chan.go:176 +0xba fp=0xc042151f20 sp=0xc042151e70
runtime.chansend1(0x970300, 0x5105fcc3b06b8383, 0xc042151fb0)
	C:/Go/src/runtime/chan.go:113 +0x4d fp=0xc042151f60 sp=0xc042151f20
vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x1f8)
	src/vendor/github.com/Microsoft/go-winio/file.go:133 +0xea fp=0xc042151fd8 sp=0xc042151f60
runtime.goexit()
	C:/Go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc042151fe0 sp=0xc042151fd8
created by vendor/github.com/Microsoft/go-winio.initIo
	src/vendor/github.com/Microsoft/go-winio/file.go:57 +0x87
```

Other google results for this error were submitted directly to golang/go, so i don't know if this is an issue with Golang's runtime or an issue with this library.

It seems to happen randomly, based on synchronisation state of other parts of the program.

`go version go1.8 windows/amd64`

**EDIT:** Simplified report using the latest information.

**Comment by mappu** [comment]
Hi,

I have a minimal test case that reproduces this issue in maybe 1 of 10 executions.

The program creates a named pipe to listen on; does some background work; and then connects to the named pipe.

It also involves one other third-party CGO library that seems to exacerbate the issue, but, this third-party library does not appear anywhere in the stack traces.

Source for reproducer:
- https://github.com/mappu/winio-zstd-panic/blob/master/src/winio-zstd-panic/main.go 

Go-get installer:
- `go get github.com/mappu/winio-zstd-panic/src/winio-zstd-panic`

Example full stack trace:
- https://gist.github.com/mappu/d1972e6e59596e98c7d3b677b18e5237

**Comment by mappu** [comment]
After some research in ticket https://github.com/golang/go/issues/19468#issuecomment-286297678 , i think this library has not been updated for the stricter `runtime.SetFinalizer` in Go 1.8. This is causing the library to use uninitialised memory.
